# Generated by Django 4.2.16 on 2024-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='quote_code',
            field=models.CharField(max_length=15),
        ),
    ]
