# Generated by Django 4.2.16 on 2024-09-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_quote_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(choices=[('SV', 'SV'), ('GT', 'GT')], max_length=3, null=True),
        ),
    ]
