# Generated by Django 4.2.16 on 2024-09-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hdd_Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('uom', models.CharField(choices=[('GB', 'GB'), ('TB', 'TB')], default='TB', max_length=2)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
