# Generated by Django 4.2.16 on 2024-09-27 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hdd_capacity_alter_customer_updated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nas_Accessory_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('active', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nas_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=12)),
                ('launch_year', models.PositiveSmallIntegerField()),
                ('warranty_years', models.PositiveSmallIntegerField()),
                ('is_rackable', models.BooleanField(default=False)),
                ('has_redundant_ps', models.BooleanField(default=False)),
                ('hdd_internal_slots', models.PositiveSmallIntegerField()),
                ('ram_default', models.PositiveSmallIntegerField()),
                ('ram_max', models.PositiveSmallIntegerField()),
                ('ram_slots', models.PositiveSmallIntegerField()),
                ('pci_slots_qty', models.PositiveSmallIntegerField()),
                ('hdd_max_slots', models.PositiveSmallIntegerField()),
                ('hdd_max_expansion_units_qty', models.PositiveSmallIntegerField()),
                ('oneGb_nic_qty', models.PositiveSmallIntegerField()),
                ('tenGb_compatible', models.BooleanField(default=False)),
                ('tenGb_nic_qty', models.PositiveSmallIntegerField()),
                ('m2_compatible', models.BooleanField(default=False)),
                ('m2_internal_slots_qty', models.PositiveSmallIntegerField()),
                ('msrp', models.FloatField(default=0.0)),
                ('weight_in_pounds', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.maker')),
            ],
        ),
        migrations.CreateModel(
            name='Nas_Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('msrp', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.nas_accessory_category')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.maker')),
            ],
        ),
    ]
