# Generated by Django 4.2.16 on 2024-09-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_nas_model_onegb_nic_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas_model',
            name='cores_per_cpu',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nas_model',
            name='cpu_model',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='nas_model',
            name='cpu_qty',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
