# Generated by Django 4.2.16 on 2024-09-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_nas_model_cores_per_cpu_nas_model_cpu_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nas_model',
            old_name='ram_default_MB',
            new_name='ram_default_GB',
        ),
        migrations.RenameField(
            model_name='nas_model',
            old_name='ram_max_MB',
            new_name='ram_max_GB',
        ),
    ]
