# Generated by Django 4.2.16 on 2024-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_ram_default_mb_nas_model_ram_default_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas_model',
            name='oneGb_nic_qty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
