# Generated by Django 4.2.16 on 2024-10-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_nas_model_onegb_nic_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nas_Model',
        ),
    ]
