# Generated by Django 4.2.16 on 2024-10-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_nas_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nas_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=12)),
                ('launch_year', models.PositiveSmallIntegerField()),
                ('warranty_years', models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (5, 5)], default=2)),
                ('cpu_model', models.CharField(max_length=25, null=True)),
                ('cpu_qty', models.PositiveBigIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('cores_per_cpu', models.PositiveBigIntegerField(choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12)], default=1)),
                ('weight_in_pounds', models.FloatField(default=0.0)),
                ('msrp', models.FloatField(default=0.0)),
                ('is_rackable', models.BooleanField(default=False)),
                ('has_redundant_ps', models.BooleanField(default=False)),
                ('pci_slots_qty', models.PositiveSmallIntegerField(default=0)),
                ('m2_compatible', models.BooleanField(default=False)),
                ('m2_internal_slots_qty', models.PositiveSmallIntegerField(default=0)),
                ('hdd_internal_slots', models.PositiveSmallIntegerField(default=1)),
                ('ram_default_GB', models.PositiveSmallIntegerField(default=2)),
                ('ram_max_GB', models.PositiveSmallIntegerField(default=0)),
                ('ram_slots', models.PositiveSmallIntegerField(default=0)),
                ('hdd_max_slots', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (4, 4), (5, 5), (6, 6), (8, 8), (12, 12)], default=0)),
                ('hdd_max_expansion_units_qty', models.PositiveSmallIntegerField(null=True)),
                ('oneGb_nic_qty', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0)),
                ('tenGb_compatible', models.BooleanField(default=False)),
                ('tenGb_nic_qty', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.maker')),
            ],
        ),
    ]
