# Generated by Django 4.2.16 on 2024-10-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_nas_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nas_model',
            name='hdd_internal_slots',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (4, 4), (5, 5), (6, 6), (8, 8), (12, 12)], default=1),
        ),
        migrations.AlterField(
            model_name='nas_model',
            name='hdd_max_slots',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
