# Generated by Django 4.2.16 on 2024-10-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_nas_model_hdd_internal_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nas_accessory',
            name='maker',
        ),
    ]
