# Generated by Django 4.2.16 on 2024-10-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_nas_accessory_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas_accessory',
            name='nas_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.nas_model'),
        ),
    ]
