# Generated by Django 4.2.16 on 2024-10-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_nas_accessory_nas_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nas_accessory',
            name='nas_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.nas_model'),
        ),
    ]
